name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use 'windows-latest' or 'macos-latest' if needed

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 11
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Ensure the Java version is at least 11

      # Run the command
      - name: Run ci-cd-check.jar
        run: java -jar ci-cd-check.jar remote